# Generated by Django 5.0.4 on 2024-10-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
